[package]
name = "jsonugget"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rfd = "0.12.0"
serde_json = "1.0.107"
dirs = { version = "5.0.1", features = [] }
chrono = "0.4.31"
